name: TikTok to YouTube Bot

on:
  schedule:
    - cron: '0 * * * *' # ၁ နာရီတစ်ခါ ပတ်မယ်
  workflow_dispatch: # လက်နဲ့ စမ်းနှိပ်လို့ရအောင်

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: |
          npm install
          sudo wget https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -O /usr/local/bin/yt-dlp
          sudo chmod a+rx /usr/local/bin/yt-dlp
      - name: Run Bot
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: node bot.js
